INSERT INTO APN_CONF (
    APN_CONF,
    CONTEXT_IDENTIFIER,
    SERVED_PARTY_IP_ADDRESS_0,
    SERVED_PARTY_IP_ADDRESS_1,
    SERVED_PARTY_IP_ADDRESS_2,
    PDN_TYPE,
    SERVICE_SELECTION,
    QOS_CLASS_IDENTIFIER,
    PRIORITY_LEVEL,
    PRE_EMPTION_CAPABILITY,
    PRE_EMPTION_VULNERABILITY,
    VPLMN_DYNAMIC_ADDR_ALLOWED,
    MIP_HOME_AGENT_ADDRESS1,
    MIP_HOME_AGENT_ADDRESS2,
    MIP_HOME_AGENT_HOST,
    MIP6_HOME_LINK_PREFIX,
    PDN_GW_ALLOCATION_TYPE,
    GPP_CHARGING_CHARACTERISTIC,
    MAX_REQUESTED_BANDWIDTH_UL,
    MAX_REQUESTED_BANDWIDTH_DL,
    SP_SERVICE_SELECTION,
    SP_MIP_HOME_AGENT_ADDR1,
    SP_MIP_HOME_AGENT_ADDR2,
    SP_MIP_HOME_AGENT_HOST,
    SP_MIP6_HOME_LINK_PREFIX,
    SP_VISITED_NETWORK_ID,
    IMSI_SPON,
    IMSI_HOME
)
SELECT
    -- APN_CONF: VARCHAR2(1500) - Generating a long random hex string like the sample
    DBMS_RANDOM.STRING('X', 256),
    -- CONTEXT_IDENTIFIER: NUMBER(5,0) - Random identifier
    TRUNC(DBMS_RANDOM.VALUE(1, 99999)),
    -- SERVED_PARTY_IP_ADDRESS_0: VARCHAR2(24) - Random IPv4 address
    TRUNC(DBMS_RANDOM.VALUE(1, 254)) || '.' || TRUNC(DBMS_RANDOM.VALUE(0, 255)) || '.' || TRUNC(DBMS_RANDOM.VALUE(0, 255)) || '.' || TRUNC(DBMS_RANDOM.VALUE(1, 254)),
    -- SERVED_PARTY_IP_ADDRESS_1: VARCHAR2(24) - Random IPv4 address
    TRUNC(DBMS_RANDOM.VALUE(1, 254)) || '.' || TRUNC(DBMS_RANDOM.VALUE(0, 255)) || '.' || TRUNC(DBMS_RANDOM.VALUE(0, 255)) || '.' || TRUNC(DBMS_RANDOM.VALUE(1, 254)),
    -- SERVED_PARTY_IP_ADDRESS_2: VARCHAR2(24) - Random IPv4 address
    TRUNC(DBMS_RANDOM.VALUE(1, 254)) || '.' || TRUNC(DBMS_RANDOM.VALUE(0, 255)) || '.' || TRUNC(DBMS_RANDOM.VALUE(0, 255)) || '.' || TRUNC(DBMS_RANDOM.VALUE(1, 254)),
    -- PDN_TYPE: NUMBER(2,0) - Small integer, often a type code
    TRUNC(DBMS_RANDOM.VALUE(0, 4)),
    -- SERVICE_SELECTION: VARCHAR2(120) - Creating a unique, realistic-looking service name
    'service' || LEVEL || '.apn.syniverse.com',
    -- QOS_CLASS_IDENTIFIER: NUMBER(4,0) - QCI is usually a small integer
    TRUNC(DBMS_RANDOM.VALUE(1, 9)),
    -- PRIORITY_LEVEL: NUMBER(10,0) - Priority is often 1-15
    TRUNC(DBMS_RANDOM.VALUE(1, 15)),
    -- PRE_EMPTION_CAPABILITY: NUMBER(2,0) - Typically a 0 or 1 flag
    ROUND(DBMS_RANDOM.VALUE(0, 1)),
    -- PRE_EMPTION_VULNERABILITY: NUMBER(2,0) - Typically a 0 or 1 flag
    ROUND(DBMS_RANDOM.VALUE(0, 1)),
    -- VPLMN_DYNAMIC_ADDR_ALLOWED: NUMBER(2,0) - Typically a 0 or 1 flag
    ROUND(DBMS_RANDOM.VALUE(0, 1)),
    -- MIP_HOME_AGENT_ADDRESS1: VARCHAR2(24) - Random IPv4
    TRUNC(DBMS_RANDOM.VALUE(1, 254)) || '.' || TRUNC(DBMS_RANDOM.VALUE(0, 255)) || '.' || TRUNC(DBMS_RANDOM.VALUE(0, 255)) || '.' || TRUNC(DBMS_RANDOM.VALUE(1, 254)),
    -- MIP_HOME_AGENT_ADDRESS2: VARCHAR2(24) - Random IPv4
    TRUNC(DBMS_RANDOM.VALUE(1, 254)) || '.' || TRUNC(DBMS_RANDOM.VALUE(0, 255)) || '.' || TRUNC(DBMS_RANDOM.VALUE(0, 255)) || '.' || TRUNC(DBMS_RANDOM.VALUE(1, 254)),
    -- MIP_HOME_AGENT_HOST: VARCHAR2(256) - Unique hostname
    'mip-host-' || LEVEL || '.syniverse.com',
    -- MIP6_HOME_LINK_PREFIX: VARCHAR2(256) - Random IPv6 style prefix
    DBMS_RANDOM.STRING('X', 4) || ':' || DBMS_RANDOM.STRING('X', 4) || '::/64',
    -- PDN_GW_ALLOCATION_TYPE: NUMBER(2,0) - Small integer type
    TRUNC(DBMS_RANDOM.VALUE(0, 3)),
    -- GPP_CHARGING_CHARACTERISTIC: VARCHAR2(8) - Random 4-digit hex string
    DBMS_RANDOM.STRING('X', 4),
    -- MAX_REQUESTED_BANDWIDTH_UL: NUMBER(15,0) - Large number for bandwidth
    TRUNC(DBMS_RANDOM.VALUE(50000000, 200000000)),
    -- MAX_REQUESTED_BANDWIDTH_DL: NUMBER(15,0) - Large number for bandwidth
    TRUNC(DBMS_RANDOM.VALUE(100000000, 500000000)),
    -- SP_SERVICE_SELECTION: VARCHAR2(120) - Another service name
    'sp-service' || LEVEL || '.apn.net',
    -- SP_MIP_HOME_AGENT_ADDR1: VARCHAR2(24) - Random IPv4
    TRUNC(DBMS_RANDOM.VALUE(1, 254)) || '.' || TRUNC(DBMS_RANDOM.VALUE(0, 255)) || '.' || TRUNC(DBMS_RANDOM.VALUE(0, 255)) || '.' || TRUNC(DBMS_RANDOM.VALUE(1, 254)),
    -- SP_MIP_HOME_AGENT_ADDR2: VARCHAR2(24) - Random IPv4
    TRUNC(DBMS_RANDOM.VALUE(1, 254)) || '.' || TRUNC(DBMS_RANDOM.VALUE(0, 255)) || '.' || TRUNC(DBMS_RANDOM.VALUE(0, 255)) || '.' || TRUNC(DBMS_RANDOM.VALUE(1, 254)),
    -- SP_MIP_HOME_AGENT_HOST: VARCHAR2(24) - Shorter unique hostname
    SUBSTR('sp-host-' || LEVEL || '.net', 1, 24),
    -- SP_MIP6_HOME_LINK_PREFIX: VARCHAR2(256) - Random IPv6 style prefix
    DBMS_RANDOM.STRING('X', 4) || ':' || DBMS_RANDOM.STRING('X', 4) || ':' || DBMS_RANDOM.STRING('X', 4) || '::/48',
    -- SP_VISITED_NETWORK_ID: VARCHAR2(24) - Random network ID
    'network-' || DBMS_RANDOM.STRING('X', 10),
    -- IMSI_SPON: VARCHAR2(20) - Random 15-digit number as a string
    TO_CHAR(TRUNC(DBMS_RANDOM.VALUE(100000000000000, 999999999999999))),
    -- IMSI_HOME: VARCHAR2(20) - Random 15-digit number as a string
    TO_CHAR(TRUNC(DBMS_RANDOM.VALUE(100000000000000, 999999999999999)))
FROM
    dual
CONNECT BY
    LEVEL <= 1300000;

-- Commit the transaction to make the changes permanent
COMMIT;
